name: Main Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

    #   - name: a Sync files
    #     uses: SamKirkland/FTP-Deploy-Action@v4.3.4 
    #     with:
    #         server: ftp.mmsdev.site
    #         port: 21
    #         localPath: './dist'
    #         username: ${{ secrets.FTP_USERNAME }}
    #         password: ${{ secrets.FTP_PASSWORD }}

    #   - name: Upload production-ready build files
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: production-files
    #       path: ./dist

      - name: Upload Production Server
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ftp.mmsdev.site
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: './dist'
        #   remotePath: '/var/www/****'